<?xml version="1.0" encoding="utf-8"?><Database Name="hds0230549_db" Class="DS_ShopThemeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=hds-023.hichina.com;Initial Catalog=hds0230549_db;Persist Security Info=True;User ID=hds0230549" SettingsObjectName="Com.DianShi.Model.ShopConfig.Properties.Settings" SettingsPropertyName="hds0230549_dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DS_ShopTheme" Member="DS_ShopTheme">
    <Type Name="DS_ShopTheme">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Always" IsVersion="true" />
      <Column Name="ThemeName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SignType" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SignImg" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SignBgColor" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ComNameShow" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ComNameCss" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Thume" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="AdSigleImg" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="AdSigleTxt" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AdMutiImg1" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="AdMutiImg2" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="AdMutiImg3" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="AdMutiImg4" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="AdMutiTxt1" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AdMutiTxt2" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AdMutiTxt3" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AdMutiTxt4" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="InnerBg" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="OuterBg" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NavBg" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NavBgNormal" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NavNormalCss" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NavBgSel" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NavSelCss" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NavMargin" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>