#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3615
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.DianShi.Model.Member
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="DianShi")]
	public partial class DS_CompanyInfoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDS_CompanyInfo(DS_CompanyInfo instance);
    partial void UpdateDS_CompanyInfo(DS_CompanyInfo instance);
    partial void DeleteDS_CompanyInfo(DS_CompanyInfo instance);
    #endregion
		
		public DS_CompanyInfoDataContext() : 
				base(global::Com.DianShi.Model.Member.Properties.Settings.Default.DianShiConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DS_CompanyInfoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DS_CompanyInfoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DS_CompanyInfoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DS_CompanyInfoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DS_CompanyInfo> DS_CompanyInfo
		{
			get
			{
				return this.GetTable<DS_CompanyInfo>();
			}
		}
	}
	
	[Table(Name="dbo.DS_CompanyInfo")]
	public partial class DS_CompanyInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _MenberID;
		
		private string _CompanyName;
		
		private string _MainIndustry;
		
		private string _Province;
		
		private string _City;
		
		private System.Nullable<byte> _MemberType;
		
		private string _OfferService;
		
		private string _BuyService;
		
		private string _BusinessType;
		
		private string _BusinessModel;
		
		private string _MainProducts;
		
		private string _Profile;
		
		private string _MainMarket;
		
		private string _AnnualTurnover;
		
		private string _MajorCustomers;
		
		private string _BrandName;
		
		private string _Employees;
		
		private string _AnnualExport;
		
		private string _ServiceIndustry;
		
		private bool _Agents;
		
		private string _AgentsLevel;
		
		private string _StorageArea;
		
		private string _RegisteredCapital;
		
		private string _RegistrationArea;
		
		private string _YearEstablished;
		
		private string _LegalRepresentative;
		
		private string _Bank;
		
		private string _Account;
		
		private string _BusinessAddress;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMenberIDChanging(string value);
    partial void OnMenberIDChanged();
    partial void OnCompanyNameChanging(string value);
    partial void OnCompanyNameChanged();
    partial void OnMainIndustryChanging(string value);
    partial void OnMainIndustryChanged();
    partial void OnProvinceChanging(string value);
    partial void OnProvinceChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnMemberTypeChanging(System.Nullable<byte> value);
    partial void OnMemberTypeChanged();
    partial void OnOfferServiceChanging(string value);
    partial void OnOfferServiceChanged();
    partial void OnBuyServiceChanging(string value);
    partial void OnBuyServiceChanged();
    partial void OnBusinessTypeChanging(string value);
    partial void OnBusinessTypeChanged();
    partial void OnBusinessModelChanging(string value);
    partial void OnBusinessModelChanged();
    partial void OnMainProductsChanging(string value);
    partial void OnMainProductsChanged();
    partial void OnProfileChanging(string value);
    partial void OnProfileChanged();
    partial void OnMainMarketChanging(string value);
    partial void OnMainMarketChanged();
    partial void OnAnnualTurnoverChanging(string value);
    partial void OnAnnualTurnoverChanged();
    partial void OnMajorCustomersChanging(string value);
    partial void OnMajorCustomersChanged();
    partial void OnBrandNameChanging(string value);
    partial void OnBrandNameChanged();
    partial void OnEmployeesChanging(string value);
    partial void OnEmployeesChanged();
    partial void OnAnnualExportChanging(string value);
    partial void OnAnnualExportChanged();
    partial void OnServiceIndustryChanging(string value);
    partial void OnServiceIndustryChanged();
    partial void OnAgentsChanging(bool value);
    partial void OnAgentsChanged();
    partial void OnAgentsLevelChanging(string value);
    partial void OnAgentsLevelChanged();
    partial void OnStorageAreaChanging(string value);
    partial void OnStorageAreaChanged();
    partial void OnRegisteredCapitalChanging(string value);
    partial void OnRegisteredCapitalChanged();
    partial void OnRegistrationAreaChanging(string value);
    partial void OnRegistrationAreaChanged();
    partial void OnYearEstablishedChanging(string value);
    partial void OnYearEstablishedChanged();
    partial void OnLegalRepresentativeChanging(string value);
    partial void OnLegalRepresentativeChanged();
    partial void OnBankChanging(string value);
    partial void OnBankChanged();
    partial void OnAccountChanging(string value);
    partial void OnAccountChanged();
    partial void OnBusinessAddressChanging(string value);
    partial void OnBusinessAddressChanged();
    #endregion
		
		public DS_CompanyInfo()
		{
			OnCreated();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, IsVersion=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_MenberID", DbType="NChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string MenberID
		{
			get
			{
				return this._MenberID;
			}
			set
			{
				if ((this._MenberID != value))
				{
					this.OnMenberIDChanging(value);
					this.SendPropertyChanging();
					this._MenberID = value;
					this.SendPropertyChanged("MenberID");
					this.OnMenberIDChanged();
				}
			}
		}
		
		[Column(Storage="_CompanyName", DbType="NChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this.OnCompanyNameChanging(value);
					this.SendPropertyChanging();
					this._CompanyName = value;
					this.SendPropertyChanged("CompanyName");
					this.OnCompanyNameChanged();
				}
			}
		}
		
		[Column(Storage="_MainIndustry", DbType="NChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string MainIndustry
		{
			get
			{
				return this._MainIndustry;
			}
			set
			{
				if ((this._MainIndustry != value))
				{
					this.OnMainIndustryChanging(value);
					this.SendPropertyChanging();
					this._MainIndustry = value;
					this.SendPropertyChanged("MainIndustry");
					this.OnMainIndustryChanged();
				}
			}
		}
		
		[Column(Storage="_Province", DbType="NChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string Province
		{
			get
			{
				return this._Province;
			}
			set
			{
				if ((this._Province != value))
				{
					this.OnProvinceChanging(value);
					this.SendPropertyChanging();
					this._Province = value;
					this.SendPropertyChanged("Province");
					this.OnProvinceChanged();
				}
			}
		}
		
		[Column(Storage="_City", DbType="NChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[Column(Storage="_MemberType", DbType="TinyInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<byte> MemberType
		{
			get
			{
				return this._MemberType;
			}
			set
			{
				if ((this._MemberType != value))
				{
					this.OnMemberTypeChanging(value);
					this.SendPropertyChanging();
					this._MemberType = value;
					this.SendPropertyChanged("MemberType");
					this.OnMemberTypeChanged();
				}
			}
		}
		
		[Column(Storage="_OfferService", DbType="NChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string OfferService
		{
			get
			{
				return this._OfferService;
			}
			set
			{
				if ((this._OfferService != value))
				{
					this.OnOfferServiceChanging(value);
					this.SendPropertyChanging();
					this._OfferService = value;
					this.SendPropertyChanged("OfferService");
					this.OnOfferServiceChanged();
				}
			}
		}
		
		[Column(Storage="_BuyService", DbType="NChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string BuyService
		{
			get
			{
				return this._BuyService;
			}
			set
			{
				if ((this._BuyService != value))
				{
					this.OnBuyServiceChanging(value);
					this.SendPropertyChanging();
					this._BuyService = value;
					this.SendPropertyChanged("BuyService");
					this.OnBuyServiceChanged();
				}
			}
		}
		
		[Column(Storage="_BusinessType", DbType="NChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string BusinessType
		{
			get
			{
				return this._BusinessType;
			}
			set
			{
				if ((this._BusinessType != value))
				{
					this.OnBusinessTypeChanging(value);
					this.SendPropertyChanging();
					this._BusinessType = value;
					this.SendPropertyChanged("BusinessType");
					this.OnBusinessTypeChanged();
				}
			}
		}
		
		[Column(Storage="_BusinessModel", DbType="NChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string BusinessModel
		{
			get
			{
				return this._BusinessModel;
			}
			set
			{
				if ((this._BusinessModel != value))
				{
					this.OnBusinessModelChanging(value);
					this.SendPropertyChanging();
					this._BusinessModel = value;
					this.SendPropertyChanged("BusinessModel");
					this.OnBusinessModelChanged();
				}
			}
		}
		
		[Column(Storage="_MainProducts", DbType="NChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string MainProducts
		{
			get
			{
				return this._MainProducts;
			}
			set
			{
				if ((this._MainProducts != value))
				{
					this.OnMainProductsChanging(value);
					this.SendPropertyChanging();
					this._MainProducts = value;
					this.SendPropertyChanged("MainProducts");
					this.OnMainProductsChanged();
				}
			}
		}
		
		[Column(Storage="_Profile", DbType="NChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string Profile
		{
			get
			{
				return this._Profile;
			}
			set
			{
				if ((this._Profile != value))
				{
					this.OnProfileChanging(value);
					this.SendPropertyChanging();
					this._Profile = value;
					this.SendPropertyChanged("Profile");
					this.OnProfileChanged();
				}
			}
		}
		
		[Column(Storage="_MainMarket", DbType="NChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string MainMarket
		{
			get
			{
				return this._MainMarket;
			}
			set
			{
				if ((this._MainMarket != value))
				{
					this.OnMainMarketChanging(value);
					this.SendPropertyChanging();
					this._MainMarket = value;
					this.SendPropertyChanged("MainMarket");
					this.OnMainMarketChanged();
				}
			}
		}
		
		[Column(Storage="_AnnualTurnover", DbType="NChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string AnnualTurnover
		{
			get
			{
				return this._AnnualTurnover;
			}
			set
			{
				if ((this._AnnualTurnover != value))
				{
					this.OnAnnualTurnoverChanging(value);
					this.SendPropertyChanging();
					this._AnnualTurnover = value;
					this.SendPropertyChanged("AnnualTurnover");
					this.OnAnnualTurnoverChanged();
				}
			}
		}
		
		[Column(Storage="_MajorCustomers", DbType="NChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string MajorCustomers
		{
			get
			{
				return this._MajorCustomers;
			}
			set
			{
				if ((this._MajorCustomers != value))
				{
					this.OnMajorCustomersChanging(value);
					this.SendPropertyChanging();
					this._MajorCustomers = value;
					this.SendPropertyChanged("MajorCustomers");
					this.OnMajorCustomersChanged();
				}
			}
		}
		
		[Column(Storage="_BrandName", DbType="NChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string BrandName
		{
			get
			{
				return this._BrandName;
			}
			set
			{
				if ((this._BrandName != value))
				{
					this.OnBrandNameChanging(value);
					this.SendPropertyChanging();
					this._BrandName = value;
					this.SendPropertyChanged("BrandName");
					this.OnBrandNameChanged();
				}
			}
		}
		
		[Column(Storage="_Employees", DbType="NChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string Employees
		{
			get
			{
				return this._Employees;
			}
			set
			{
				if ((this._Employees != value))
				{
					this.OnEmployeesChanging(value);
					this.SendPropertyChanging();
					this._Employees = value;
					this.SendPropertyChanged("Employees");
					this.OnEmployeesChanged();
				}
			}
		}
		
		[Column(Storage="_AnnualExport", DbType="NChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string AnnualExport
		{
			get
			{
				return this._AnnualExport;
			}
			set
			{
				if ((this._AnnualExport != value))
				{
					this.OnAnnualExportChanging(value);
					this.SendPropertyChanging();
					this._AnnualExport = value;
					this.SendPropertyChanged("AnnualExport");
					this.OnAnnualExportChanged();
				}
			}
		}
		
		[Column(Storage="_ServiceIndustry", DbType="NChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string ServiceIndustry
		{
			get
			{
				return this._ServiceIndustry;
			}
			set
			{
				if ((this._ServiceIndustry != value))
				{
					this.OnServiceIndustryChanging(value);
					this.SendPropertyChanging();
					this._ServiceIndustry = value;
					this.SendPropertyChanged("ServiceIndustry");
					this.OnServiceIndustryChanged();
				}
			}
		}
		
		[Column(Storage="_Agents", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool Agents
		{
			get
			{
				return this._Agents;
			}
			set
			{
				if ((this._Agents != value))
				{
					this.OnAgentsChanging(value);
					this.SendPropertyChanging();
					this._Agents = value;
					this.SendPropertyChanged("Agents");
					this.OnAgentsChanged();
				}
			}
		}
		
		[Column(Storage="_AgentsLevel", DbType="NChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string AgentsLevel
		{
			get
			{
				return this._AgentsLevel;
			}
			set
			{
				if ((this._AgentsLevel != value))
				{
					this.OnAgentsLevelChanging(value);
					this.SendPropertyChanging();
					this._AgentsLevel = value;
					this.SendPropertyChanged("AgentsLevel");
					this.OnAgentsLevelChanged();
				}
			}
		}
		
		[Column(Storage="_StorageArea", DbType="NChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string StorageArea
		{
			get
			{
				return this._StorageArea;
			}
			set
			{
				if ((this._StorageArea != value))
				{
					this.OnStorageAreaChanging(value);
					this.SendPropertyChanging();
					this._StorageArea = value;
					this.SendPropertyChanged("StorageArea");
					this.OnStorageAreaChanged();
				}
			}
		}
		
		[Column(Storage="_RegisteredCapital", DbType="NChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string RegisteredCapital
		{
			get
			{
				return this._RegisteredCapital;
			}
			set
			{
				if ((this._RegisteredCapital != value))
				{
					this.OnRegisteredCapitalChanging(value);
					this.SendPropertyChanging();
					this._RegisteredCapital = value;
					this.SendPropertyChanged("RegisteredCapital");
					this.OnRegisteredCapitalChanged();
				}
			}
		}
		
		[Column(Storage="_RegistrationArea", DbType="NChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string RegistrationArea
		{
			get
			{
				return this._RegistrationArea;
			}
			set
			{
				if ((this._RegistrationArea != value))
				{
					this.OnRegistrationAreaChanging(value);
					this.SendPropertyChanging();
					this._RegistrationArea = value;
					this.SendPropertyChanged("RegistrationArea");
					this.OnRegistrationAreaChanged();
				}
			}
		}
		
		[Column(Storage="_YearEstablished", DbType="NChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string YearEstablished
		{
			get
			{
				return this._YearEstablished;
			}
			set
			{
				if ((this._YearEstablished != value))
				{
					this.OnYearEstablishedChanging(value);
					this.SendPropertyChanging();
					this._YearEstablished = value;
					this.SendPropertyChanged("YearEstablished");
					this.OnYearEstablishedChanged();
				}
			}
		}
		
		[Column(Storage="_LegalRepresentative", DbType="NChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string LegalRepresentative
		{
			get
			{
				return this._LegalRepresentative;
			}
			set
			{
				if ((this._LegalRepresentative != value))
				{
					this.OnLegalRepresentativeChanging(value);
					this.SendPropertyChanging();
					this._LegalRepresentative = value;
					this.SendPropertyChanged("LegalRepresentative");
					this.OnLegalRepresentativeChanged();
				}
			}
		}
		
		[Column(Storage="_Bank", DbType="NChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string Bank
		{
			get
			{
				return this._Bank;
			}
			set
			{
				if ((this._Bank != value))
				{
					this.OnBankChanging(value);
					this.SendPropertyChanging();
					this._Bank = value;
					this.SendPropertyChanged("Bank");
					this.OnBankChanged();
				}
			}
		}
		
		[Column(Storage="_Account", DbType="NChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string Account
		{
			get
			{
				return this._Account;
			}
			set
			{
				if ((this._Account != value))
				{
					this.OnAccountChanging(value);
					this.SendPropertyChanging();
					this._Account = value;
					this.SendPropertyChanged("Account");
					this.OnAccountChanged();
				}
			}
		}
		
		[Column(Storage="_BusinessAddress", DbType="NChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string BusinessAddress
		{
			get
			{
				return this._BusinessAddress;
			}
			set
			{
				if ((this._BusinessAddress != value))
				{
					this.OnBusinessAddressChanging(value);
					this.SendPropertyChanging();
					this._BusinessAddress = value;
					this.SendPropertyChanged("BusinessAddress");
					this.OnBusinessAddressChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
