#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1891
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.DianShi.Model.Member
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="DianShi")]
	public partial class View_MembersDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public View_MembersDataContext() : 
				base(global::Com.DianShi.Model.Member.Properties.Settings.Default.DianShiConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public View_MembersDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public View_MembersDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public View_MembersDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public View_MembersDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<View_Members> View_Members
		{
			get
			{
				return this.GetTable<View_Members>();
			}
		}
	}
	
	[Table(Name="dbo.View_Members")]
	public partial class View_Members
	{
		
		private int _ID;
		
		private string _UserID;
		
		private string _Password;
		
		private string _Email;
		
		private string _TrueName;
		
		private string _Department;
		
		private string _Position;
		
		private string _QQ;
		
		private string _Gender;
		
		private string _Phone;
		
		private string _Fax;
		
		private string _Mobile;
		
		private string _HomePage;
		
		private bool _EmailValidate;
		
		private bool _MobileValidate;
		
		private string _CompanyName;
		
		private System.Nullable<byte> _BusinessType;
		
		private string _BusinessModel;
		
		private string _CapitalType;
		
		private System.Nullable<double> _RegisteredCapital;
		
		private short _YearEstablished;
		
		private string _RegistrationArea;
		
		private string _Province;
		
		private string _City;
		
		private string _County;
		
		private string _BusinessAddress;
		
		private string _ZipCode;
		
		private byte _MemberType;
		
		private string _OfferService;
		
		private string _BuyService;
		
		private string _MainIndustry;
		
		private string _Profile;
		
		private string _LegalRepresentative;
		
		private string _Bank;
		
		private string _Account;
		
		private string _StorageArea;
		
		private System.Nullable<byte> _Employees;
		
		private System.Nullable<byte> _StudyEmployees;
		
		private string _BrandName;
		
		private System.Nullable<int> _Monthly;
		
		private string _MonthlyUnit;
		
		private System.Nullable<byte> _AnnualTurnover;
		
		private System.Nullable<byte> _AnnualExport;
		
		private System.Nullable<byte> _AnnualImports;
		
		private string _MSCer;
		
		private string _QualityControl;
		
		private string _MainMarket;
		
		private string _MajorCustomers;
		
		private System.Nullable<bool> _OEM;
		
		private string _ComImg;
		
		private string _MapNid;
		
		public View_Members()
		{
		}
		
		[Column(Storage="_ID", DbType="Int NOT NULL", IsDbGenerated=true, IsVersion=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[Column(Storage="_UserID", DbType="NVarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[Column(Storage="_Password", DbType="NVarChar(120) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[Column(Storage="_Email", DbType="NVarChar(100) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[Column(Storage="_TrueName", DbType="NVarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string TrueName
		{
			get
			{
				return this._TrueName;
			}
			set
			{
				if ((this._TrueName != value))
				{
					this._TrueName = value;
				}
			}
		}
		
		[Column(Storage="_Department", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this._Department = value;
				}
			}
		}
		
		[Column(Storage="_Position", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this._Position = value;
				}
			}
		}
		
		[Column(Storage="_QQ", DbType="NVarChar(15)", UpdateCheck=UpdateCheck.Never)]
		public string QQ
		{
			get
			{
				return this._QQ;
			}
			set
			{
				if ((this._QQ != value))
				{
					this._QQ = value;
				}
			}
		}
		
		[Column(Storage="_Gender", DbType="NVarChar(2) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
		
		[Column(Storage="_Phone", DbType="NVarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
		
		[Column(Storage="_Fax", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
		
		[Column(Storage="_Mobile", DbType="NVarChar(11)", UpdateCheck=UpdateCheck.Never)]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this._Mobile = value;
				}
			}
		}
		
		[Column(Storage="_HomePage", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string HomePage
		{
			get
			{
				return this._HomePage;
			}
			set
			{
				if ((this._HomePage != value))
				{
					this._HomePage = value;
				}
			}
		}
		
		[Column(Storage="_EmailValidate", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool EmailValidate
		{
			get
			{
				return this._EmailValidate;
			}
			set
			{
				if ((this._EmailValidate != value))
				{
					this._EmailValidate = value;
				}
			}
		}
		
		[Column(Storage="_MobileValidate", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool MobileValidate
		{
			get
			{
				return this._MobileValidate;
			}
			set
			{
				if ((this._MobileValidate != value))
				{
					this._MobileValidate = value;
				}
			}
		}
		
		[Column(Storage="_CompanyName", DbType="NVarChar(100) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this._CompanyName = value;
				}
			}
		}
		
		[Column(Storage="_BusinessType", DbType="TinyInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<byte> BusinessType
		{
			get
			{
				return this._BusinessType;
			}
			set
			{
				if ((this._BusinessType != value))
				{
					this._BusinessType = value;
				}
			}
		}
		
		[Column(Storage="_BusinessModel", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string BusinessModel
		{
			get
			{
				return this._BusinessModel;
			}
			set
			{
				if ((this._BusinessModel != value))
				{
					this._BusinessModel = value;
				}
			}
		}
		
		[Column(Storage="_CapitalType", DbType="NVarChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string CapitalType
		{
			get
			{
				return this._CapitalType;
			}
			set
			{
				if ((this._CapitalType != value))
				{
					this._CapitalType = value;
				}
			}
		}
		
		[Column(Storage="_RegisteredCapital", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> RegisteredCapital
		{
			get
			{
				return this._RegisteredCapital;
			}
			set
			{
				if ((this._RegisteredCapital != value))
				{
					this._RegisteredCapital = value;
				}
			}
		}
		
		[Column(Storage="_YearEstablished", DbType="SmallInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public short YearEstablished
		{
			get
			{
				return this._YearEstablished;
			}
			set
			{
				if ((this._YearEstablished != value))
				{
					this._YearEstablished = value;
				}
			}
		}
		
		[Column(Storage="_RegistrationArea", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string RegistrationArea
		{
			get
			{
				return this._RegistrationArea;
			}
			set
			{
				if ((this._RegistrationArea != value))
				{
					this._RegistrationArea = value;
				}
			}
		}
		
		[Column(Storage="_Province", DbType="NVarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Province
		{
			get
			{
				return this._Province;
			}
			set
			{
				if ((this._Province != value))
				{
					this._Province = value;
				}
			}
		}
		
		[Column(Storage="_City", DbType="NVarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[Column(Storage="_County", DbType="NVarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string County
		{
			get
			{
				return this._County;
			}
			set
			{
				if ((this._County != value))
				{
					this._County = value;
				}
			}
		}
		
		[Column(Storage="_BusinessAddress", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string BusinessAddress
		{
			get
			{
				return this._BusinessAddress;
			}
			set
			{
				if ((this._BusinessAddress != value))
				{
					this._BusinessAddress = value;
				}
			}
		}
		
		[Column(Storage="_ZipCode", DbType="NVarChar(6)", UpdateCheck=UpdateCheck.Never)]
		public string ZipCode
		{
			get
			{
				return this._ZipCode;
			}
			set
			{
				if ((this._ZipCode != value))
				{
					this._ZipCode = value;
				}
			}
		}
		
		[Column(Storage="_MemberType", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte MemberType
		{
			get
			{
				return this._MemberType;
			}
			set
			{
				if ((this._MemberType != value))
				{
					this._MemberType = value;
				}
			}
		}
		
		[Column(Storage="_OfferService", DbType="NVarChar(100) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string OfferService
		{
			get
			{
				return this._OfferService;
			}
			set
			{
				if ((this._OfferService != value))
				{
					this._OfferService = value;
				}
			}
		}
		
		[Column(Storage="_BuyService", DbType="NVarChar(100) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string BuyService
		{
			get
			{
				return this._BuyService;
			}
			set
			{
				if ((this._BuyService != value))
				{
					this._BuyService = value;
				}
			}
		}
		
		[Column(Storage="_MainIndustry", DbType="NVarChar(100) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string MainIndustry
		{
			get
			{
				return this._MainIndustry;
			}
			set
			{
				if ((this._MainIndustry != value))
				{
					this._MainIndustry = value;
				}
			}
		}
		
		[Column(Storage="_Profile", DbType="NVarChar(1800)", UpdateCheck=UpdateCheck.Never)]
		public string Profile
		{
			get
			{
				return this._Profile;
			}
			set
			{
				if ((this._Profile != value))
				{
					this._Profile = value;
				}
			}
		}
		
		[Column(Storage="_LegalRepresentative", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string LegalRepresentative
		{
			get
			{
				return this._LegalRepresentative;
			}
			set
			{
				if ((this._LegalRepresentative != value))
				{
					this._LegalRepresentative = value;
				}
			}
		}
		
		[Column(Storage="_Bank", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string Bank
		{
			get
			{
				return this._Bank;
			}
			set
			{
				if ((this._Bank != value))
				{
					this._Bank = value;
				}
			}
		}
		
		[Column(Storage="_Account", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string Account
		{
			get
			{
				return this._Account;
			}
			set
			{
				if ((this._Account != value))
				{
					this._Account = value;
				}
			}
		}
		
		[Column(Storage="_StorageArea", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string StorageArea
		{
			get
			{
				return this._StorageArea;
			}
			set
			{
				if ((this._StorageArea != value))
				{
					this._StorageArea = value;
				}
			}
		}
		
		[Column(Storage="_Employees", DbType="TinyInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<byte> Employees
		{
			get
			{
				return this._Employees;
			}
			set
			{
				if ((this._Employees != value))
				{
					this._Employees = value;
				}
			}
		}
		
		[Column(Storage="_StudyEmployees", DbType="TinyInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<byte> StudyEmployees
		{
			get
			{
				return this._StudyEmployees;
			}
			set
			{
				if ((this._StudyEmployees != value))
				{
					this._StudyEmployees = value;
				}
			}
		}
		
		[Column(Storage="_BrandName", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string BrandName
		{
			get
			{
				return this._BrandName;
			}
			set
			{
				if ((this._BrandName != value))
				{
					this._BrandName = value;
				}
			}
		}
		
		[Column(Storage="_Monthly", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> Monthly
		{
			get
			{
				return this._Monthly;
			}
			set
			{
				if ((this._Monthly != value))
				{
					this._Monthly = value;
				}
			}
		}
		
		[Column(Storage="_MonthlyUnit", DbType="NVarChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string MonthlyUnit
		{
			get
			{
				return this._MonthlyUnit;
			}
			set
			{
				if ((this._MonthlyUnit != value))
				{
					this._MonthlyUnit = value;
				}
			}
		}
		
		[Column(Storage="_AnnualTurnover", DbType="TinyInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<byte> AnnualTurnover
		{
			get
			{
				return this._AnnualTurnover;
			}
			set
			{
				if ((this._AnnualTurnover != value))
				{
					this._AnnualTurnover = value;
				}
			}
		}
		
		[Column(Storage="_AnnualExport", DbType="TinyInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<byte> AnnualExport
		{
			get
			{
				return this._AnnualExport;
			}
			set
			{
				if ((this._AnnualExport != value))
				{
					this._AnnualExport = value;
				}
			}
		}
		
		[Column(Storage="_AnnualImports", DbType="TinyInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<byte> AnnualImports
		{
			get
			{
				return this._AnnualImports;
			}
			set
			{
				if ((this._AnnualImports != value))
				{
					this._AnnualImports = value;
				}
			}
		}
		
		[Column(Storage="_MSCer", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string MSCer
		{
			get
			{
				return this._MSCer;
			}
			set
			{
				if ((this._MSCer != value))
				{
					this._MSCer = value;
				}
			}
		}
		
		[Column(Storage="_QualityControl", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string QualityControl
		{
			get
			{
				return this._QualityControl;
			}
			set
			{
				if ((this._QualityControl != value))
				{
					this._QualityControl = value;
				}
			}
		}
		
		[Column(Storage="_MainMarket", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string MainMarket
		{
			get
			{
				return this._MainMarket;
			}
			set
			{
				if ((this._MainMarket != value))
				{
					this._MainMarket = value;
				}
			}
		}
		
		[Column(Storage="_MajorCustomers", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string MajorCustomers
		{
			get
			{
				return this._MajorCustomers;
			}
			set
			{
				if ((this._MajorCustomers != value))
				{
					this._MajorCustomers = value;
				}
			}
		}
		
		[Column(Storage="_OEM", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> OEM
		{
			get
			{
				return this._OEM;
			}
			set
			{
				if ((this._OEM != value))
				{
					this._OEM = value;
				}
			}
		}
		
		[Column(Storage="_ComImg", DbType="NVarChar(250) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string ComImg
		{
			get
			{
				return this._ComImg;
			}
			set
			{
				if ((this._ComImg != value))
				{
					this._ComImg = value;
				}
			}
		}
		
		[Column(Storage="_MapNid", DbType="NVarChar(30)", UpdateCheck=UpdateCheck.Never)]
		public string MapNid
		{
			get
			{
				return this._MapNid;
			}
			set
			{
				if ((this._MapNid != value))
				{
					this._MapNid = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
