<?xml version="1.0" encoding="utf-8"?>
<Database Name="ds" Class="DS_OrderDetailDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PC2011102412YEG\sql0801;Initial Catalog=ds;Integrated Security=True" SettingsObjectName="Com.DianShi.Model.Transaction.Properties.Settings" SettingsPropertyName="dsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DS_OrderDetail" Member="DS_OrderDetail">
    <Type Name="DS_OrderDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Always" IsVersion="true" />
      <Column Name="OrderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProName" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>