<?xml version="1.0" encoding="utf-8"?>
<Database Name="ds" Class="DS_PurchaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PC2011102412YEG\sql0801;Initial Catalog=ds;Integrated Security=True" SettingsObjectName="Com.DianShi.Model.Transaction.Properties.Settings" SettingsPropertyName="dsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DS_Purchase" Member="DS_Purchase">
    <Type Name="DS_Purchase">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MemberID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>