<?xml version="1.0" encoding="utf-8"?><Database Name="hds0230549_db" Class="DS_ShopConfigDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=hds-023.hichina.com;Initial Catalog=hds0230549_db;Persist Security Info=True;User ID=hds0230549" SettingsObjectName="Com.DianShi.Model.ShopConfig.Properties.Settings" SettingsPropertyName="hds0230549_dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DS_ShopConfig" Member="DS_ShopConfig">
    <Type Name="DS_ShopConfig">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Always" IsVersion="true" />
      <Column Name="MemberID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SignType" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SignImg" Type="System.String" DbType="NVarChar(350)" CanBeNull="true" />
      <Column Name="SignBgColor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ComNameShow" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ComNameCss" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="AdSigleImg" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="AdSigleTxt" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AdMutiImg1" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="AdMutiImg2" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="AdMutiImg3" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="AdMutiImg4" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="AdMutiTxt1" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AdMutiTxt2" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AdMutiTxt3" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AdMutiTxt4" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AdType" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="AdShow" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="InnerBg" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="OuterBg" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MenuBg" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SelectedMenu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NormalMenu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NmColor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SelmColor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>