<?xml version="1.0" encoding="utf-8"?>
<Database Name="hds0230549_db" Class="DS_ShopConfigDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=hds-023.hichina.com;Initial Catalog=hds0230549_db;Persist Security Info=True;User ID=hds0230549" SettingsObjectName="Com.DianShi.Model.ShopConfig.Properties.Settings" SettingsPropertyName="hds0230549_dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DS_ShopConfig" Member="DS_ShopConfig">
    <Type Name="DS_ShopConfig">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Always" IsVersion="true" />
      <Column Name="MemberID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Sign" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MenuBg" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SelectedMenu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NormalMenu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NmColor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SelmColor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RollImg1" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="RollImg2" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="RollImg3" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SignType" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="ComNameStyle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ComNameDisplay" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>